chain_width                = 130
fn_single_line             = true
group_imports              = "StdExternalCrate"
ignore                     = ["src/deps", "Cargo.toml"]
imports_granularity        = "Module"
match_block_trailing_comma = true
max_width                  = 150

single_line_if_else_max_width = 100
